obj-$(CONFIG_MMC_SUNXI)                      += sunxi_mmc_host.o
sunxi_mmc_host-$(CONFIG_MMC_SUNXI_V4P1X)     += sunxi-mmc-v4p1x.o
sunxi_mmc_host-$(CONFIG_MMC_SUNXI_V4P00X)    += sunxi-mmc-v4p00x.o
sunxi_mmc_host-$(CONFIG_MMC_SUNXI_V4P5X)     += sunxi-mmc-v4p5x.o
sunxi_mmc_host-$(CONFIG_MMC_SUNXI_V5P3X)     += sunxi-mmc-v5p3x.o
sunxi_mmc_host-$(CONFIG_MMC_SUNXI)           += sunxi-mmc.o sunxi-mmc-debug.o sunxi-mmc-export.o sunxi-mmc-panic.o


